language: node_js
node_js:
- node

addons:
  ssh_known_hosts: 66.42.50.117

install: npm install

before_install:
- openssl aes-256-cbc -K $encrypted_efbcfcc9eef6_key -iv $encrypted_efbcfcc9eef6_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
  on:
    branch: master