# see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/ for more hints
language: node_js

node_js:
  - "stable"
  
cache:
  directories:
  - node_modules

script:
  - npm test

env:
  global:
  - 'SFTP_USER=root'
  - 'SFTP_PASSWORD=A]8f+fGv#b_WD]U@'
after_success:
- curl --ftp-create-dirs
       -T downloadWord.js
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@66.42.50.117/var/www/filename
