# see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/ for more hints
language: node_js

node_js:
  - "stable"
  
cache:
  directories:
  - node_modules

script:
  - npm test

env:
  global:
  - "FTP_USER=root"
  - "FTP_PASSWORD=A]8f+fGv#b_WD]U@"
after_success:
  "curl -T words.txt -u $FTP_USER:$FTP_PASSWORD ftp://var/www/html"
