language: node_js

node_js:
- node

addons:
  ssh_known_hosts: 66.42.50.117

  
before_install:
- openssl aes-256-cbc -K $encrypted_efbcfcc9eef6_key -iv $encrypted_efbcfcc9eef6_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- ssh-add deploy_key

install: npm install

deploy:
  provider: script
  skip_cleanup: true
  script: sh ./bin/deploy.sh
  on:
    branch: master
